spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db?serverTimezone=UTC
    username: root
    password: 123456
  main:
    banner-mode: off
# 开启Mp的日志，输出到控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id # 这句话等同于在User类里面的相应设定
      table-prefix: tbl_ # 意思就是为了匹配数据库中的表名，这样就可以在代码中的实体类前面统一全局加上tbl_前缀
      # 下面这三行就是相当于User类中的TableLogic部份
      logic-delete-field: deleted #
      logic-not-delete-value: 0
      logic-delete-value: 1

